name: ${name}
version: ${version}
main: ${group}.PrimeSeller
author: destroydevs
authors:
  - golovin12
api-version: 1.21
description: Скупщик предметов
softdepend: [ Vault, CoinsEngine, PlaceholderAPI ]

commands:
  seller:
    aliases:
      - 'sell'
      - 'buyer'
  autoseller:
    aliases:
      - 'autosell'
      - 'asell'
  primeseller:
    aliases:
      - 'psell'

permissions:
  primeseller.user:
    description: Права игрока
    children:
      primeseller.seller: true
      primeseller.autoseller: true
  primeseller.seller:
    description: Право открытия меню продажи
    default: true
  primeseller.autoseller:
    description: Право открытия меню автопродажи
    default: true
  primeseller.autosell.*:
    description: Лимит на предметы в автопродаже
    default: false
  primeseller.autosell.bypass:
    description: Отключение лимита предметов в автопродаже
    default: op
  primeseller.admin:
    description: Доступ к командам админа
    default: op
