name: PrimeSeller-Fork
version: '1.4.0'
main: me.byteswing.primeseller.PrimeSeller
api-version: 1.21
softdepend: [ Vault, CoinsEngine, PlaceholderAPI ]
author: destroydevs, golovin12
website: https://github.com/flyawaymaking
description: |
  PrimeSeller - Fork maintained by flyawaymaking
  Original plugin by destroydevs
  Licensed under Apache License 2.0

commands:
  seller:
    aliases:
      - 'sell'
      - 'buyer'
  autoseller:
    aliases:
      - 'autosell'
      - 'asell'
  primeseller:
    aliases:
      - 'psell'

permissions:
  primeseller.user:
    description: Права игрока
    children:
      primeseller.seller: true
      primeseller.autoseller: true
  primeseller.seller:
    description: Право открытия меню продажи
    default: true
  primeseller.autoseller:
    description: Право открытия меню автопродажи
    default: true
  primeseller.autosell.*:
    description: Лимит на предметы в автопродаже
    default: false
  primeseller.autosell.bypass:
    description: Отключение лимита предметов в автопродаже
    default: op
  primeseller.admin:
    description: Доступ к командам админа
    default: op
